openapi: 3.0.0
info:
  title: AI Humanoid Robotics Textbook API
  description: API for the AI Humanoid Robotics Textbook platform
  version: 1.0.0
servers:
  - url: https://api.ai-humanoid-textbook.com/v1
    description: Production server
  - url: https://staging-api.ai-humanoid-textbook.com/v1
    description: Staging server

paths:
  /modules:
    get:
      summary: List all textbook modules
      description: Retrieve a list of all 4 modules in the textbook
      responses:
        '200':
          description: List of modules
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Module'
        '400':
          description: Invalid request parameters

  /modules/{moduleId}:
    get:
      summary: Get module details
      description: Retrieve details of a specific module including its chapters
      parameters:
        - name: moduleId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the module
      responses:
        '200':
          description: Module details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Module'
        '404':
          description: Module not found

  /chapters:
    get:
      summary: List all chapters
      description: Retrieve a list of all chapters across all modules
      responses:
        '200':
          description: List of chapters
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Chapter'
        '400':
          description: Invalid request parameters

  /chapters/{chapterId}:
    get:
      summary: Get chapter details
      description: Retrieve details of a specific chapter including content and learning outcomes
      parameters:
        - name: chapterId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the chapter
      responses:
        '200':
          description: Chapter details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Chapter'
        '404':
          description: Chapter not found

  /users/{userId}/progress:
    get:
      summary: Get user progress
      description: Retrieve progress information for a specific user
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the user
      responses:
        '200':
          description: User progress information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProgress'
        '404':
          description: User not found

    post:
      summary: Update user progress
      description: Update progress for a specific chapter
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProgressUpdate'
      responses:
        '200':
          description: Progress updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Progress'
        '400':
          description: Invalid progress update data
        '404':
          description: User or chapter not found

  /translations/{contentId}:
    get:
      summary: Get translated content
      description: Retrieve translated content for a specific module or chapter
      parameters:
        - name: contentId
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the content (module or chapter)
        - name: language
          in: query
          required: true
          schema:
            type: string
          description: Target language code (e.g., 'ur' for Urdu)
      responses:
        '200':
          description: Translated content
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Translation'
        '404':
          description: Content or translation not found

  /citations:
    get:
      summary: List citations
      description: Retrieve a list of all citations used in the textbook
      parameters:
        - name: module
          in: query
          required: false
          schema:
            type: string
          description: Filter citations by module
        - name: chapter
          in: query
          required: false
          schema:
            type: string
          description: Filter citations by chapter
      responses:
        '200':
          description: List of citations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Citation'
        '400':
          description: Invalid request parameters

components:
  schemas:
    Module:
      type: object
      required:
        - id
        - title
        - description
        - order
      properties:
        id:
          type: string
          description: Unique identifier for the module
          example: "module1"
        title:
          type: string
          description: Display title of the module
          example: "The Robotic Nervous System"
        description:
          type: string
          description: Brief description of the module content
          example: "Introduction to ROS 2 and its role in humanoid robotics"
        order:
          type: integer
          description: Sequential order of the module (1-4)
          example: 1
        chapters:
          type: array
          items:
            $ref: '#/components/schemas/Chapter'
          description: List of chapters in this module

    Chapter:
      type: object
      required:
        - id
        - moduleId
        - title
        - content
        - order
      properties:
        id:
          type: string
          description: Unique identifier for the chapter
          example: "module1-chapter1"
        moduleId:
          type: string
          description: Reference to the parent module
          example: "module1"
        title:
          type: string
          description: Display title of the chapter
          example: "Introduction to ROS 2 Architecture"
        content:
          type: string
          description: Main content of the chapter in Markdown format
          example: "# Introduction to ROS 2\n\nROS 2 (Robot Operating System 2)..."
        learningOutcomes:
          type: array
          items:
            type: string
          description: List of learning outcomes for the chapter
          example: ["Understand ROS 2 node architecture", "Explain the pub/sub pattern"]
        summary:
          type: string
          description: Chapter summary
          example: "This chapter introduced ROS 2 architecture concepts..."
        order:
          type: integer
          description: Sequential order of the chapter within the module (1-3)
          example: 1
        textDiagrams:
          type: array
          items:
            type: string
          description: Text descriptions of diagrams included in the chapter

    UserProgress:
      type: object
      properties:
        userId:
          type: string
          description: Unique identifier for the user
          example: "user123"
        enrolledModules:
          type: array
          items:
            type: string
          description: List of module IDs the user is studying
          example: ["module1", "module2"]
        progress:
          type: array
          items:
            $ref: '#/components/schemas/Progress'

    Progress:
      type: object
      properties:
        chapterId:
          type: string
          description: Reference to the chapter
          example: "module1-chapter1"
        completed:
          type: boolean
          description: Whether the chapter is completed
          example: true
        completionDate:
          type: string
          format: date-time
          description: When the chapter was completed
          example: "2023-10-15T10:30:00Z"
        notes:
          type: string
          description: User's notes on the chapter
          example: "Great explanation of pub/sub pattern"
        rating:
          type: integer
          description: User's rating of the chapter (1-5)
          example: 5

    ProgressUpdate:
      type: object
      required:
        - chapterId
        - completed
      properties:
        chapterId:
          type: string
          description: Reference to the chapter
          example: "module1-chapter1"
        completed:
          type: boolean
          description: Whether the chapter is completed
          example: true
        notes:
          type: string
          description: User's notes on the chapter
          example: "Great explanation of pub/sub pattern"
        rating:
          type: integer
          description: User's rating of the chapter (1-5)
          minimum: 1
          maximum: 5
          example: 5

    Translation:
      type: object
      required:
        - id
        - sourceId
        - sourceType
        - language
        - content
      properties:
        id:
          type: string
          description: Unique identifier for the translation
          example: "trans-module1-en-ur"
        sourceId:
          type: string
          description: Reference to the original content
          example: "module1"
        sourceType:
          type: string
          enum: [CHAPTER, MODULE]
          description: Type of source content
          example: "MODULE"
        language:
          type: string
          description: Language code
          example: "ur"
        content:
          type: string
          description: Translated content in Markdown format
          example: "# مقدمہ\n\nروبوٹ آپریٹنگ سسٹم 2..."

    Citation:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: string
          description: Unique identifier for the citation
          example: "cit-ros2-paper-2023"
        title:
          type: string
          description: Title of the cited work
          example: "ROS 2: An Open-Source Scalable Robot Operating System"
        authors:
          type: array
          items:
            type: string
          description: List of authors
          example: ["Smith, J.", "Johnson, A.", "Williams, R."]
        publicationDate:
          type: string
          format: date
          description: Date of publication
          example: "2023-05-15"
        source:
          type: string
          description: Where the work was published
          example: "IEEE Robotics and Automation Letters"
        url:
          type: string
          format: uri
          description: URL if available
          example: "https://example.com/paper/123"
        doi:
          type: string
          description: Digital Object Identifier if available
          example: "10.1109/LRA.2023.1234567"
        citationType:
          type: string
          enum: [BOOK, ARTICLE, CONFERENCE, WEBSITE]
          description: Type of source
          example: "ARTICLE"